if(PROJECT_IS_TOP_LEVEL)
  set(CMAKE_INSTALL_INCLUDEDIR include/operon CACHE PATH "")
endif()

include(CMakePackageConfigHelpers)
include(GNUInstallDirs)

# find_package(<package>) call for consumers to find this project
set(package operon)

install(
    TARGETS operon_operon
    EXPORT operonTargets
    FILE_SET operon_headers DESTINATION "${CMAKE_INSTALL_INCLUDEDIR}" COMPONENT operon_Development
    FILE_SET operon_detail_headers DESTINATION "${CMAKE_INSTALL_INCLUDEDIR}" COMPONENT operon_Development
    RUNTIME #
    COMPONENT operon_Runtime
    LIBRARY #
    COMPONENT operon_Runtime
    NAMELINK_COMPONENT operon_Development
    ARCHIVE #
    COMPONENT operon_Development
    INCLUDES #
    DESTINATION "${CMAKE_INSTALL_INCLUDEDIR}"
)

# Generated by GenerateExportHeader and required by installed public headers.
install(
    FILES "${PROJECT_BINARY_DIR}/export/operon/operon_export.hpp"
    DESTINATION "${CMAKE_INSTALL_INCLUDEDIR}/operon"
    COMPONENT operon_Development
)

# Target installation is declared above with FILE_SET operon_headers.

write_basic_package_version_file(
    "${package}ConfigVersion.cmake"
    COMPATIBILITY SameMajorVersion
)

# Allow package maintainers to freely override the path for the configs
set(
    operon_INSTALL_CMAKEDIR "${CMAKE_INSTALL_DATADIR}/${package}"
    CACHE PATH "CMake package config location relative to the install prefix"
)
mark_as_advanced(operon_INSTALL_CMAKEDIR)

configure_file(
    "${CMAKE_CURRENT_SOURCE_DIR}/cmake/install-config.cmake.in"
    "${CMAKE_CURRENT_BINARY_DIR}/${package}Config.cmake"
    @ONLY
)

install(
    FILES "${CMAKE_CURRENT_BINARY_DIR}/${package}Config.cmake"
    DESTINATION "${operon_INSTALL_CMAKEDIR}"
    COMPONENT operon_Development
)

install(
    FILES "${PROJECT_BINARY_DIR}/${package}ConfigVersion.cmake"
    DESTINATION "${operon_INSTALL_CMAKEDIR}"
    COMPONENT operon_Development
)

install(
    EXPORT operonTargets
    NAMESPACE operon::
    DESTINATION "${operon_INSTALL_CMAKEDIR}"
    COMPONENT operon_Development
)

if(PROJECT_IS_TOP_LEVEL)
  include(CPack)
endif()
