name: documentation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27
    - name: Configure documentation build
      run: nix develop .#docs -c cmake -S . -B build-docs -DBUILD_DOCS=ON

    - name: Build documentation
      run: nix develop .#docs -c cmake --build build-docs --target docs -j2

    - uses: actions/upload-pages-artifact@v3
      with:
        path: build-docs/docs/html

  deploy:
    if: github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest

    steps:
    - id: deployment
      uses: actions/deploy-pages@v4
