name: tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27

    - name: Configure
      run: nix develop -c cmake --preset build-linux -B build -DUSE_SINGLE_PRECISION=ON -Doperon_DEVELOPER_MODE=ON

    - name: Build test binary
      run: nix develop -c cmake --build build --target operon_test -j4

    - name: Run tests
      run: nix develop -c ctest --test-dir build --output-on-failure -j4
